version: '3'

services:
  todo-api:
    container_name: todo-heroku-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=docker
      - PORT=1323
      - DATABASE_SOURCE=postgres
      - POSTGRES_HOST=todo-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_SSL=disable
    ports:
      - "1323:1323"
    depends_on:
      - todo-db
    networks:
      - todo-network
  todo-db:
    image: postgres
    volumes:
      - ./internal/infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - todo-network
networks:
  todo-network:
    driver: bridge